-- OUTER JOIN

-- EMP 테이블에는 DEPTNO 가 10, 20, 30 만 존재하고 
-- DEPT 테이블에는 DEPTNO 가 10, 20, 30, 40 이 존재

-- DEPT 테이블에만 존재하는 40번도 JOIN에 참여
SELECT *
FROM EMP RIGHT OUTER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO

-- FULL OUTER JOIN 하려면 LEFT OUTER JOIN 과 RIGHT OUTER JOIN의 UNION 연산으로 해결
SELECT *
FROM EMP LEFT OUTER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
UNION
SELECT *
FROM EMP RIGHT OUTER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO